### ISSUE TITLE
Bugs while working with camunda modeler version 4.11.1

### ISSUE THREAD

**Issue by Nelly1313** [camunda/camunda-modeler-linter-plugin#19] opened 2021-11-19 07:17 UTC
The linter plugin starts having bugs if used with camunda modeler version 4.11.1. It's still possible to check if a process has start and end events and it does realize if an event is missing and even updates the counter but the error is not shown in the diagram itself.

**Comment by nikku** [comment] 2021-11-19 08:32
Thanks for opening this issue.

Please use our existing template and add more required data:

* When did it break
* When did it work
* OS, installed plug-ins, ...

**Comment by nikku** [comment] 2021-11-24 10:19
Closing this one as invalid. I cannot reproduce your issue with a fresh version of Camunda Modeler v4.11.1 + the latest version of this plug-in.

**Closed by nikku** 2021-11-24 10:19 UTC
Labels: help wanted

**Comment by Nelly1313** [comment] 2021-11-26 12:02
I tried removing Camunda Modeler v4.11.1 and reloaded a fresh version as well as the newest version of the token simulator plugin and as soon as activating the error is reocurring. I don't know why you can't reproduce the error but it's still not working.

**Comment by Nelly1313** [comment] 2021-11-26 12:14
As you can see in the first screen, the linter plugin in combination with Camunda Modeler v 4.10 displays an error for the missing start event:
![Missing start displayed](https://user-images.githubusercontent.com/94673055/143579350-b64fdcc4-6539-4631-be5d-ea633c9120a3.png)

Using Camunda v4.11.1 the error is still processed as you can see on the error counter below the diagram, but no error is displayed in the top right corner part:



![Missing start not displayed](https://user-images.githubusercontent.com/94673055/143579471-83aa9b6a-cef1-4512-b1f8-156a8e3245ad.PNG)

**Comment by nikku** [comment] 2021-11-26 12:21
Did you consider updating your linter plug-in?

**Comment by Nelly1313** [comment] 2021-11-26 12:23
I pulled the most recent version and i tried updating the used libraries via npm update but did not manage to get the error displayed. Even writing own rules works, but not the display.

**Comment by Nelly1313** [comment] 2021-12-02 09:10
I tried installing Camunda Modeler v4.10 on another Windows computer and tried the linter plugin on this computer. I keep having the same results with the linter still not displaying an error for missing start or end event in a process.

**Comment by nikku** [comment] 2021-12-02 09:21
As you did not [provide important information we need yet](https://github.com/camunda/camunda-modeler-linter-plugin/issues/19#issuecomment-973864282) I see no way how we can further help you to resolve the issue.

**Comment by Nelly1313** [comment] 2021-12-02 09:26
Which kind of information do you need?
The error appeared using Camunda Modeler v 4.11.1 as already said. 
I used the Linter Plugin( https://github.com/camunda/camunda-modeler-linter-plugin) in the most recent version as already said. 
I provided two diagrams, one being the plugin used in combination with Camunda Modeler v.4.10 where the error is correctly displayed and the other on being Camunda Modeler v 4.11 where the error is not correctly displayed. 
What kind of additional information do you need?

**Comment by nikku** [comment] 2021-12-02 10:07
Operating system, _all_ installed plug-ins would be of great help. Please attach the information to the issue you opened (use our existing issue template!). 

![image](https://user-images.githubusercontent.com/58601/144401022-f7d1f7b2-8da4-4f32-8169-c18fb35fb0ea.png)
